# Generated by Django 3.2.19 on 2023-05-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contact_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='food/default.jpg', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_farsi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
