# Generated by Django 3.2.19 on 2023-05-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_menu_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='food_name',
            new_name='name',
        ),
    ]
